language: python
sudo: false
matrix:
    include:
        - python: 2.7
          env: TOX_ENV=py27
        - python: 3.3
          env: TOX_ENV=py33
        - python: 3.4
          env: TOX_ENV=py34
        - python: 3.5
          env: TOX_ENV=py35
        - python: pypy
          env: TOX_ENV=pypy
        - python: pypy3
          env: TOX_ENV=pypy3
install:
    - pip install cffi
    - pip install tox
    - pip install coveralls
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls
