language: python
python: '2.7'

env:
  matrix:
  - TOX_ENV=packaging
  - TOX_ENV=py27
  - TOX_ENV=pypy
  - TOX_ENV=py33
  - TOX_ENV=py34

install:
  # Travis doesn't provide Python 3.4, install it.
  - "[[ ${TOX_ENV} == py34 ]] && sudo add-apt-repository -y ppa:fkrull/deadsnakes || true"
  - "[[ ${TOX_ENV} == py34 ]] && sudo apt-get -y update && sudo apt-get -y install python3.4 python3.4-dev || true"
  - make dev-env

script:
  - tox -e $TOX_ENV
